import mongoose,{Schema} from "mongoose";
const eventSchema = new Schema({
    festivalName:{
        type:String,
        trim:true
    },
    eventName:{
        type:String,
        required:true,
        trim:true
    },
    organization:{
        type:String,
        required:true,
        trim:true
    },
    organizer:{
        type:Schema.Types.ObjectId,
        ref:'User',
    },
    Mode:{
        type:String,
        required:true,
        trim:true
    },
    description:{
        type:String,
        required:true,
        trim:true
    },
    startDate:{
        type:Date,
        required:true
    },
    location:{
        type:String,
        required:true,
        trim:true
    },
    category:{
        type:String,
        required:true,
    },
    sports:{
        type:String,
    },
    others:{
        type:String
    },
    maxParticipants:{
        type:Number,
        required:true,
        default:0
    },
    rules:{
        type:Array,
        default:[]
    },
    poster:{
        url:String,
        public_id:String
    },
    eventPeople:{
        members:{
            type:Array,
            default:[{name:"",role:'Organizer'}]
        },
        participants:{
            type:Array,
            default:[]
        }
    }
},{
    timestamps:true
})

export const Event=mongoose.model('Event',eventSchema);